// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odjkscasttatqjxguitq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kamtzY2FzdHRhdHFqeGd1aXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTM4NzYsImV4cCI6MjA2NTcyOTg3Nn0.oOsu9aRkfgAyEk6hQNp5wOBKmX06l1EriNPSC1-ASV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);